### ISSUE TITLE
new release v0.3 imminent

### ISSUE THREAD

**Issue by dehesselle** [dehesselle/vmmctl#7]
Hey @nihilisticpandemonium,

I want to give you a heads-up that big changes are coming - I think for the better! There is a pre-release of the next version ([v0.3-rc.1](https://github.com/dehesselle/virtctl/tree/v0.3-rc.1) available that I'm going to deploy to my boxes to see if anything comes up that I didn't catch during the last days.

It's save to try it since it can co-exist with the older v0.2 due to renaming. (On the other hand, they are incompatible. But migrating a single VM from v0.2 to v0.3 is easy.)

If you have any comments, let me know.

**Comment by nihilistzsche** [comment]
Oh yes 0.3 looks a lot better, does not look like it will require any patches or anything else to work out of the box on Arch!  Will be updating the PKGBUILD shortly to test 0.3 out and will push it to the AUR later today or tomorrow if it checks out.

**Comment by nihilistzsche** [comment]
Indeed the only differences between my PKGBUILD and your readme is that as a package I install the systemd service things into /usr/lib/systemd/system, but this is all handled as part of the packaging process and does not require any external edits.

**Comment by nihilistzsche** [comment]
Sorry for the message spam but I feel confident enough after the couple of tests I did that I went ahead and pushed the PKGBUILD with 0.3rc1 tagged.  Let me know when you release 0.3 proper and Ill push a "virtctl" non-git package to the AUR as well.

**Comment by dehesselle** [comment]
It's fine, I don't feel spammed :-). Thank you for your continued interest.

Sadly, today I found an issue (#8, trivial to fix) that lead to another issue (#9, not too hard either, but I need to be careful) that I'll definitely want to fix for v0.3. There will be a rc2 in the next few days. I apologize for causing you (at least) double the work in case you already packaged rc1.

**Comment by nihilistzsche** [comment]
It will just be a version bump and this is what rc's are for :)

**Comment by dehesselle** [comment]
v0.3-rc.2 - this is it🤞

**Comment by nihilistzsche** [comment]
v0.3-rc.2 pushed to the AUR :)

**Comment by dehesselle** [comment]
After having reinstalled my Linux box at home and migrating all my VM at work from kvm@... to virtctl@..., I'm giving the green light. The rc.2 is the final v0.3 release.
(I just did two more commits past v0.3, but they are only of minor documentational nature.)
